require_relative './../../wurk/random_port'

module Wurk
  module Devise
    class InstallGenerator < Rails::Generators::Base
      def add_gems
        append_to_file 'Gemfile', "gem 'bcrypt'\ngem 'devise'"
      end

      def set_action_mailer
        inject_into_file "config/environments/development.rb", before: /end\Z/ do
          "\n  # generated by wurk:devise:config\n  config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }\n"
        end
      end

      def protect_from_forgery
        inject_into_class 'app/controllers/application_controller.rb', ApplicationController do
          "  protect_from_forgery prepend: true\n" 
        end
      end

      def set_port
        gsub_file 'config/puma.rb', /ENV.fetch\("PORT"\) { 3000 }/ do
          port = Wurk::RandomPort.get
          "ENV.fetch(\"PORT\") { #{port} }"
        end
      end
    end
  end
end
